"use client"

import { useRef, useState } from "react"
import { UniverseCanvas, NexusParticleLogo } from "@/components/universe-canvas"
import { ArrowRight, Cable, CheckCircle2, ChevronDown, CircleDot, Cloud, Download, Eye, Laptop, MapPin, Menu, Network, Printer, Router, Server, ShieldCheck, Signal, SlidersHorizontal, Smartphone, Sparkles, Wifi, X, Cpu, HardDrive, MemoryStick, Globe, DollarSign, FileText, Volume2, VolumeX, Activity, LockKeyhole, BadgeCheck } from "lucide-react"

const infrastructure = [
  { icon: Server, type: "SERVIDORES Y CONECTIVIDAD", title: "Enterprise Rack Server", detail: "Servidor central · Dilan", accent: "cyan", specs: ["Intel Xeon Silver 4310 · 12 cores", "64 GB ECC DDR4 RAM", "IP: 192.168.10.10 · 1 Gbps", "Rack 42U · UTP Cat 6"] },
  { icon: Signal, type: "SERVIDORES Y CONECTIVIDAD", title: "Módem ADSL Alta Velocidad", detail: "Backbone de acceso", accent: "cyan", specs: ["ADSL2+ · 100 Mbps downlink", "IP WAN dinámica · NAT firewall", "IP LAN: 192.168.10.1", "Uplink Cat 6 blindado"] },
  { icon: Router, type: "DISPOSITIVOS INTERMEDIOS", title: "Cisco Switching Core", detail: "Router principal · Kevin", accent: "violet", specs: ["Cisco Catalyst 9300 · 48 puertos", "StackWise · switching 1 Gbps", "IP gestión: 192.168.10.2", "VLAN 10/20/30 · PoE+"] },
  { icon: Wifi, type: "DISPOSITIVOS INTERMEDIOS", title: "Access Points Wi-Fi 6", detail: "Cobertura empresarial", accent: "violet", specs: ["802.11ax · 4x4 MU-MIMO", "2.4/5 GHz · 1.2 Gbps", "IP: 192.168.20.10–12", "Backhaul PoE+ · Cat 6 UTP"] },
  { icon: Laptop, type: "DISPOSITIVOS FINALES", title: "Workstations & PCs", detail: "2 alto rendimiento · 4 oficina", accent: "blue", specs: ["Intel Core i7 · 16 GB RAM", "SSD NVMe 512 GB", "IP: 192.168.30.20–25", "NIC 1 Gbps · Cat 6 UTP"] },
  { icon: Smartphone, type: "DISPOSITIVOS FINALES", title: "Laptops Ejecutivas", detail: "2 unidades · Emmanuel", accent: "blue", specs: ["Intel Core i5 · 16 GB RAM", "Wi-Fi 6 · WPA3 Enterprise", "DHCP: 192.168.20.50–51", "Roaming empresarial seguro"] },
  { icon: Printer, type: "PERIFÉRICOS & IOT", title: "Impresión y Vigilancia IP", detail: "Red de periféricos segura", accent: "purple", specs: ["Impresora láser de red", "Cámaras IP 1080p PoE", "VLAN IoT: 192.168.40.0/24", "Cableado Cat 6 certificado"] },
  { icon: Cloud, type: "PERIFÉRICOS & IOT", title: "Conexiones Móviles", detail: "Acceso remoto controlado", accent: "purple", specs: ["VPN SSL · AES-256", "Autenticación MFA", "Pool remoto: 10.10.10.0/24", "Firewall con inspección DPI"] },
]
const budget = [["Servidor Dell PowerEdge R750", "1 unidad", "$85,000 MXN"], ["Router Empresarial MikroTik CCR1009", "1 unidad", "$12,500 MXN"], ["Switch Cisco Catalyst 2960-L 24p PoE", "1 unidad", "$18,000 MXN"], ["Access Point Ubiquiti UniFi 6 Pro", "1 unidad", "$4,200 MXN"], ["Bobina Cable UTP Cat 6a 100% Cobre", "305 m", "$3,800 MXN"], ["Patch Panel 24p + Rack Mural 12U", "1 kit", "$5,500 MXN"], ["Canaletas PVC, Conectores RJ45 y Accesorios", "Kit", "$2,500 MXN"], ["No-Break / UPS APC 1500VA", "1 unidad", "$6,000 MXN"], ["Mano de Obra, Ponchado y Configuración de Red", "Servicio integral", "$15,000 MXN"]]

const team = [["LL", "Luis Lopez Alcudia", "Lead Network Architect", "Topology Design", "cyan"], ["K", "Kevin", "Infrastructure Specialist", "Hardware & Switching", "violet"], ["D", "Dilan", "Server Administrator", "Security & Systems", "blue"], ["E", "Emmanuel", "Deployment Lead", "End-Devices & Systems", "purple"]]
function Eyebrow({ icon: Icon, children }: { icon: typeof Network; children: React.ReactNode }) { return <div className="eyebrow"><Icon size={14} /><span>{children}</span></div> }
const glossary = [["LAN","Red de Área Local que conecta dispositivos dentro de un espacio limitado."],["TCP/IP","Conjunto de protocolos que permite la comunicación entre equipos."],["Subnet","Segmento lógico de una red IP que organiza y aísla dispositivos."],["Switch","Dispositivo que conecta equipos dentro de la misma red local."],["Router","Equipo que dirige tráfico entre redes y aplica políticas de acceso."],["Patch Cord","Cable corto terminado en RJ45 para conectar paneles y equipos."],["PoE","Power over Ethernet: energía y datos por el mismo cable de red."],["VLAN","Red virtual que segmenta el tráfico lógico sobre una infraestructura física."]]
function downloadReport() { const report = `%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n4 0 obj<</Length 278>>stream\nBT /F1 18 Tf 50 740 Td (NEXUS LAN SOLUTIONS) Tj /F1 11 Tf 0 -28 Td (Reporte tecnico de infraestructura LAN) Tj 0 -24 Td (Uptime: 99.99% | Latencia ISP: 4 ms) Tj 0 -20 Td (Ancho de banda: 420 / 500 Mbps) Tj 0 -20 Td (Firewall: Activo - MikroTik CCR1009) Tj 0 -28 Td (Cumplimiento: TIA/EIA-568-C, ISO/IEC 27001, IEEE 802.3bt) Tj ET\nendstream endobj\n5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF`; const blob = new Blob([report], { type: "application/pdf" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "nexus-lan-reporte-tecnico.pdf"; link.click(); URL.revokeObjectURL(url) }
function playFx(enabled: boolean, type: "click" | "inspect") { if (!enabled || typeof window === "undefined") return; const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = "sine"; oscillator.frequency.value = type === "inspect" ? 520 : 760; gain.gain.setValueAtTime(0.0001, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.035, context.currentTime + 0.01); gain.gain.exponentialRampToValueAtTime(0.0001, context.currentTime + 0.12); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.13) }
function Glossary() { const [query, setQuery] = useState(""); const [open, setOpen] = useState<string | null>(null); const items = glossary.filter(([term, definition]) => `${term} ${definition}`.toLowerCase().includes(query.toLowerCase())); return <div className="glossary"><div className="section-heading"><div><Eyebrow icon={Network}>GLOSARIO TÉCNICO</Eyebrow><h2>Hablar la misma <span>red.</span></h2></div><input aria-label="Buscar en el glosario" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar término..." /></div><div className="glossary-list">{items.map(([term, definition]) => <button className={`glossary-item ${open === term ? "is-open" : ""}`} key={term} onClick={() => setOpen(open === term ? null : term)}><span><b>{term}</b>{open === term && <small>{definition}</small>}</span><ChevronDown size={16} /></button>)}</div></div> }

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [status, setStatus] = useState(false)
  const [activeHardware, setActiveHardware] = useState<(typeof infrastructure)[number] | null>(null)
  const [budgetOpen, setBudgetOpen] = useState(false)
  const [trafficActive, setTrafficActive] = useState(true)
  const [audioEnabled, setAudioEnabled] = useState(false)
  const [selectedNode, setSelectedNode] = useState<string | null>(null)
  const toggleAudio = () => { setAudioEnabled((enabled) => !enabled); playFx(!audioEnabled, "click") }
  const inspectNode = (node: string) => { setSelectedNode(node); playFx(audioEnabled, "inspect") }
  const nodeData: Record<string, { ip: string; ping: string; cpu: string; ram: string; ports: string }> = { Server: { ip: "192.168.10.10", ping: "2 ms", cpu: "18%", ram: "42%", ports: "8 / 12" }, "Core Switch": { ip: "192.168.10.2", ping: "1 ms", cpu: "12%", ram: "28%", ports: "18 / 24" }, Router: { ip: "192.168.10.1", ping: "4 ms", cpu: "31%", ram: "36%", ports: "6 / 8" }, "Workstations & PCs": { ip: "192.168.30.20–25", ping: "3 ms", cpu: "24%", ram: "51%", ports: "6 / 6" } }
  return <main>
    <UniverseCanvas />
    <header className="site-header"><a href="#inicio" className="brand"><span className="brand-mark"><Network size={19} /></span><span>NEXUS <b>LAN</b><small>SOLUTIONS</small></span></a><nav className={mobileOpen ? "nav-links open" : "nav-links"} aria-label="Navegación principal"><a href="#infraestructura" onClick={() => setMobileOpen(false)}>Infraestructura</a><a href="#topologia" onClick={() => setMobileOpen(false)}>Topología LAN</a><a href="#ubicacion" onClick={() => setMobileOpen(false)}>Ubicación</a><a href="#equipo" onClick={() => setMobileOpen(false)}>Equipo</a><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú"><X size={20} /></button></nav><button className="audio-button" onClick={toggleAudio} aria-label={audioEnabled ? "Silenciar efectos" : "Activar efectos de audio"}>{audioEnabled ? <Volume2 size={15} /> : <VolumeX size={15} />}</button><button className="report-nav-button" onClick={downloadReport}><Download size={14} /> Reporte PDF</button><button className="status-button" onClick={() => setStatus(!status)}><span className="live-dot" />{status ? "Red operativa" : "Ver estado de red"}<ArrowRight size={15} /></button><button className="menu-button" onClick={() => setMobileOpen(true)} aria-label="Abrir menú"><Menu size={22} /></button></header>
    <section id="inicio" className="hero shell"><div className="hero-copy"><Eyebrow icon={Sparkles}>INFRAESTRUCTURA DE NUEVA GENERACIÓN</Eyebrow><h1>Redes que <em>conectan</em><br />el futuro.</h1><p>Diseñamos y desplegamos infraestructura LAN de nivel empresarial: alto rendimiento, topologías inteligentes y seguridad sin compromisos.</p><div className="hero-actions"><a className="button-primary" href="#topologia">Explorar topología <ArrowRight size={16} /></a><button className="button-ghost report-button" onClick={downloadReport}><FileText size={15} /> Descargar Reporte Técnico (PDF)</button><a className="button-ghost" href="#infraestructura">Especificaciones técnicas <ChevronDown size={16} /></a></div><div className="hero-trust"><CheckCircle2 size={15} /><span>Arquitectura diseñada para continuidad</span><i /><span>Villahermosa, MX</span></div></div><div className="network-dashboard"><div className="dashboard-top"><span><span className="live-dot" /> LIVE / NETWORK MONITOR</span><span>NX-01 <CircleDot size={13} /></span></div><div className="dashboard-map"><div className="map-grid" /><span className="node n1" /><span className="node n2" /><span className="node n3" /><span className="node n4" /><div className="line l1" /><div className="line l2" /><div className="line l3" /><div className="line l4" /><div className="core-node"><Network size={24} /><b>CORE</b></div><div className="map-label ml1">SERVER RACK / 01</div><div className="map-label ml2">CISCO CORE / 02</div><span className="ping-ring" /></div><div className="metrics"><div><span>LATENCIA</span><strong>1<small>ms</small></strong><i className="metric-line cyan-line" /></div><div><span>UPTIME</span><strong>99.99<small>%</small></strong><i className="metric-line violet-line" /></div><div><span>ANCHO DE BANDA</span><strong>1<small>Gbps</small></strong><i className="metric-line blue-line" /></div></div></div></section>
    <section id="infraestructura" className="section shell"><div className="section-heading"><div><Eyebrow icon={SlidersHorizontal}>SISTEMA COMPLETO</Eyebrow><h2>Infraestructura <span>sin límites.</span></h2></div><p>Un ecosistema conectado, diseñado para escalar. Cada componente cumple un rol preciso dentro de nuestra arquitectura de red.</p></div><div className="infra-grid">{infrastructure.map(({ icon: Icon, type, title, detail, accent, specs }) => <article className={`infra-card ${accent}`} key={title} role="button" tabIndex={0} onClick={() => setActiveHardware({ icon: Icon, type, title, detail, accent, specs })} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setActiveHardware({ icon: Icon, type, title, detail, accent, specs }) } }}><div className="card-icon"><Icon size={21} /></div><span className="card-type">{type}</span><h3>{title}</h3><p>{detail}</p><span className="card-hint">VER ESPECIFICACIONES</span><ArrowRight className="card-arrow" size={17} /></article>)}</div></section>
    <section id="topologia" className="section shell topology-section"><div className="section-heading"><div><Eyebrow icon={Cable}>INGENIERÍA DE RED</Eyebrow><h2>La precisión está<br /><span>en los detalles.</span></h2></div><div className="topology-actions"><button className={`traffic-toggle ${trafficActive ? "active" : ""}`} onClick={() => setTrafficActive((active) => !active)}><Activity size={14} /> {trafficActive ? "Active Traffic" : "Traffic Paused"}</button><a href="#equipo" className="text-link">Conoce al equipo <ArrowRight size={15} /></a></div></div><div className="topology-layout"><div className="topology-visual"><div className="topology-header"><span>LAN TOPOLOGY / DIAGRAM</span><span className="pill">ONLINE</span></div><div className="topology-canvas"><button className="rack rack-server" onClick={() => inspectNode("Server")}><Server size={19} /><span>SERVER</span></button><button className="rack rack-switch" onClick={() => inspectNode("Core Switch")}><Router size={19} /><span>CORE SWITCH</span></button><div className={`topo-lines ${trafficActive ? "traffic-on" : "traffic-off"}`}><i /><i /><i /><i /><i /></div><div className="endpoints"><button onClick={() => inspectNode("Workstations & PCs")}><Laptop size={16} /></button><button onClick={() => inspectNode("Router")}><Printer size={16} /></button><button onClick={() => inspectNode("Router")}><Wifi size={16} /></button><button onClick={() => inspectNode("Router")}><Eye size={16} /></button></div><div className="topology-caption"><span>CAT 6 / UTP</span><span>FULL DUPLEX</span><span>1 Gbps</span></div></div></div><div className="spec-panel"><div className="spec-header"><Cable size={20} /><div><span>ESTÁNDAR DE CABLEADO</span><strong>UTP CAT 6</strong></div></div><p>Canalización estructurada para máximo rendimiento y mínima interferencia electromagnética.</p><ul><li><CheckCircle2 size={16} />Rack ergonómicamente organizado</li><li><CheckCircle2 size={16} />Rutas de cableado identificadas</li><li><CheckCircle2 size={16} />Cumplimiento de seguridad física</li><li><CheckCircle2 size={16} />Mantenimiento y escalabilidad</li></ul><div className="spec-footer"><span>PROTOCOL <b>TCP/IP</b></span><span>TOPOLOGY <b>STAR</b></span></div><button className="budget-button" onClick={() => setBudgetOpen(true)}><DollarSign size={15} /> Ver presupuesto de implementación <ArrowRight size={15} /></button></div></div><NexusParticleLogo /></section>
    <section id="monitoring" className="section shell monitoring-section"><div className="section-heading"><div><Eyebrow icon={Activity}>LIVE NETWORK HEALTH</Eyebrow><h2>Todo bajo <span>control.</span></h2></div><p>Supervisión continua del rendimiento, conectividad y postura de seguridad de la infraestructura.</p></div><div className="health-grid"><article className="health-card"><Activity size={18}/><span>UPTIME</span><strong>99.99%</strong><small>Dell PowerEdge R750</small></article><article className="health-card violet"><Signal size={18}/><span>ISP LATENCY</span><strong>4 <small>ms</small></strong><small>Telmex Fibra 500 Mbps</small></article><article className="health-card blue"><Globe size={18}/><span>BANDWIDTH USAGE</span><strong>420 <small>/ 500 Mbps</small></strong><small>84% de capacidad activa</small></article><article className="health-card green"><LockKeyhole size={18}/><span>SECURITY FIREWALL</span><strong>ACTIVE</strong><small>MikroTik CCR1009</small></article></div></section><section id="standards" className="section shell standards-section"><div className="section-heading"><div><Eyebrow icon={BadgeCheck}>COMPLIANCE & STANDARDS</Eyebrow><h2>Diseñado bajo <span>estándares.</span></h2></div></div><div className="standards-grid"><article><BadgeCheck size={23}/><div><strong>TIA/EIA-568-C</strong><span>Cableado estructurado Cat 6a</span></div></article><article><ShieldCheck size={23}/><div><strong>ISO/IEC 27001</strong><span>Seguridad y control de acceso</span></div></article><article><Wifi size={23}/><div><strong>IEEE 802.3bt</strong><span>Alimentación PoE+ para APs</span></div></article></div></section>
    <section id="ubicacion" className="location-section"><div className="shell location-layout"><div><Eyebrow icon={MapPin}>NUESTRA UBICACIÓN</Eyebrow><h2>En el centro de<br /><span>todo lo que importa.</span></h2><p>Operamos desde Villahermosa, Tabasco, conectando empresas con la infraestructura que necesitan para ir más lejos.</p><div className="address"><MapPin size={17} /><div><b>Oficinas Centrales & Datacenter</b><span>Villahermosa, Tabasco · México</span></div></div><a className="button-ghost" href="#equipo">Conocer más <ArrowRight size={15} /></a></div><div className="location-map"><div className="map-contours" /><div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" /><div className="map-pin"><MapPin size={24} /></div><span className="map-city">VILLAHERMOSA</span><span className="map-state">TABASCO, MX</span><div className="map-coords">17°59′N · 92°56′W</div></div></div></section>
    <section id="equipo" className="section shell team-section"><div className="section-heading"><div><Eyebrow icon={ShieldCheck}>EQUIPO 11 / NEXUS</Eyebrow><h2>Las personas detrás<br /><span>de la conexión.</span></h2></div><p>Especialistas que convierten la complejidad técnica en infraestructura confiable, segura y lista para el futuro.</p></div><div className="team-grid">{team.map(([initials, name, role, specialty, accent]) => <article className={`team-card ${accent}`} key={name}><div className="avatar">{initials}</div><div><h3>{name}</h3><p>{role}</p><span>{specialty}</span></div><ArrowRight size={16} /></article>)}</div></section>
    <section id="datos-generales" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Globe}>DATOS GENERALES Y UBICACIÓN</Eyebrow><h2>CBTis 163 <span>conectado.</span></h2></div><p>Infraestructura LAN empresarial para un entorno educativo y administrativo seguro, escalable y documentado.</p></div><div className="rubric-grid two"><article className="rubric-card"><span className="rubric-kicker">MISIÓN</span><h3>Conectar conocimiento con infraestructura confiable.</h3><p>Diseñar redes de alto rendimiento para estudiantes, docentes y administración.</p></article><article className="rubric-card"><span className="rubric-kicker">VISIÓN / MODELO</span><h3>Un campus preparado para el futuro.</h3><p>Diagnóstico, despliegue, soporte preventivo y crecimiento modular por VLAN.</p></article></div><div className="map-embed"><iframe title="Mapa de CBTis 163 Villahermosa" src="https://www.google.com/maps?q=CBTis%20163%20Villahermosa%20Tabasco&output=embed" loading="lazy" /></div></section>
    <section id="servidor" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Server}>SERVIDOR / FICHA TÉCNICA</Eyebrow><h2>Centro de datos <span>dedicado.</span></h2></div></div><div className="spec-table">{[["Plataforma","Rack server Intel Xeon / AMD EPYC"],["Memoria","64 GB ECC DDR4/DDR5"],["Almacenamiento","NVMe enterprise en RAID 10"],["Continuidad","Dual hot-swap PSU · UPS online"],["Sistema operativo","Windows Server 2022 o Linux Server LTS"]].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>
    <section id="dispositivos" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Laptop}>DISPOSITIVOS FINALES</Eyebrow><h2>Inventario <span>operativo.</span></h2></div></div><div className="inventory-table"><div className="inventory-head"><span>CANT.</span><span>DISPOSITIVO</span><span>USO PRINCIPAL</span></div>{[["2×","Workstations de alto rendimiento","CAD / render 3D"],["4×","PCs de escritorio medio","Administración"],["2×","Laptops profesionales","Dirección / movilidad"]].map(([a,b,c]) => <div className="inventory-row" key={b}><b>{a}</b><strong>{b}</strong><span>{c}</span></div>)}</div></section>
    <section id="equipamiento" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Router}>DISPOSITIVOS INTERMEDIOS</Eyebrow><h2>Control y acceso <span>empresarial.</span></h2></div></div><div className="rubric-grid four">{[[Router,"Enterprise Router","Firewall, NAT y VPN SSL"],[Network,"Managed Switch 24-Port PoE","VLAN, QoS y PoE+"],[Wifi,"Wi-Fi 6 Access Point","802.11ax · WPA3 Enterprise"],[Signal,"Network Hub","Distribución local de respaldo"]].map(([Icon,title,detail]) => <article className="rubric-card icon-card" key={title as string}><div className="card-icon"><Icon size={20}/></div><h3>{title as string}</h3><p>{detail as string}</p></article>)}</div></section>
    <section id="cableado" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Cable}>CABLEADO Y CONECTIVIDAD</Eyebrow><h2>Señal limpia, <span>siempre.</span></h2></div></div><div className="rubric-grid three">{[["CAT 6A","10 Gbps · 500 MHz · TIA/EIA-568"],["PATCHING","RJ45 pass-through · patch panels 24p"],["BACKBONE","Fibra óptica / ADSL · ISP 100 Mbps"]].map(([a,b]) => <article className="rubric-card" key={a}><span className="rubric-kicker">{a}</span><p>{b}</p><div className="cable-line"/></article>)}</div></section>
    <section id="perifericos" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={Printer}>OTROS DISPOSITIVOS EN RED</Eyebrow><h2>Todo conectado, <span>todo visible.</span></h2></div></div><div className="rubric-grid four">{[[Printer,"Impresoras láser de red"],[Eye,"Cámaras CCTV IP"],[Wifi,"Dispositivos Smart IoT"],[Smartphone,"Unidades móviles / tabletas"]].map(([Icon,title]) => <article className="rubric-card icon-card" key={title as string}><div className="card-icon"><Icon size={20}/></div><h3>{title as string}</h3><span className="status-dot">ONLINE / VLAN SEGURA</span></article>)}</div></section>
    <section id="ergonomia" className="section shell rubric-section"><div className="section-heading"><div><Eyebrow icon={ShieldCheck}>MOBILIARIO Y SEGURIDAD</Eyebrow><h2>Un espacio que <span>protege.</span></h2></div></div><div className="rubric-grid two"><article className="rubric-card"><h3>Infraestructura física</h3><p>6 sillas ergonómicas, escritorios modulares, aire acondicionado y gabinete rack 42U con UPS.</p></article><article className="rubric-card"><h3>Normas de cumplimiento</h3><p>TIA/EIA-568, puesta a tierra eléctrica, canaletas cerradas y ergonomía laboral.</p></article></div></section>
    <section id="conclusion" className="section shell rubric-section"><div className="conclusion-card"><Eyebrow icon={CheckCircle2}>CONCLUSIÓN TÉCNICA</Eyebrow><h2>Una LAN lista para <span>evolucionar.</span></h2><p>La implementación integra rendimiento, segmentación, seguridad y bienestar operativo. La topología estrella facilita diagnóstico y futuras ampliaciones.</p></div><Glossary /></section>
    <footer className="footer"><div className="shell footer-top"><a href="#inicio" className="brand"><span className="brand-mark"><Network size={19} /></span><span>NEXUS <b>LAN</b><small>SOLUTIONS</small></span></a><p>Infraestructura que mueve<br />el mundo.</p><div className="footer-meta"><span>CBTis 163</span><span>Clasifica y Diseña la Red LAN</span><span>Prof. Franklin Quevedo · Grupo 5º B</span></div></div><div className="shell footer-bottom"><span>© 2024 Nexus LAN Solutions. All rights reserved.</span><span>NETWORK STATUS <i className="live-dot" /> OPERATIONAL</span></div></footer>
    {budgetOpen && <div className="modal-backdrop" role="presentation" onClick={() => setBudgetOpen(false)}><section className="detail-modal budget-modal" role="dialog" aria-modal="true" aria-labelledby="budget-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setBudgetOpen(false)} aria-label="Cerrar presupuesto"><X size={18} /></button><Eyebrow icon={DollarSign}>INVERSIÓN DE INFRAESTRUCTURA</Eyebrow><h2 id="budget-title">Presupuesto <span>Estimado de Implementación LAN</span></h2><p className="modal-lead">Desglose detallado de materiales, hardware y servicios para el despliegue empresarial en Villahermosa.</p><div className="budget-table">{budget.map(([item, description, cost], index) => <div className="budget-row" key={item}><span className="budget-index">{String(index + 1).padStart(2, "0")}</span><div><strong>{item}</strong><span>{description}</span></div><b>{cost}</b></div>)}</div><div className="budget-total"><span>INVERSIÓN TOTAL</span><strong>$152,500 <small>MXN</small></strong></div><div className="budget-actions"><button className="button-primary" onClick={() => window.print()}><DollarSign size={15} /> Descargar Cotización (PDF)</button><button className="button-ghost" onClick={() => setBudgetOpen(false)}>Cerrar</button></div></section></div>}
    {selectedNode && <div className="drawer-backdrop" role="presentation" onClick={() => setSelectedNode(null)}><aside className="inspection-drawer" role="dialog" aria-modal="true" aria-labelledby="inspection-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedNode(null)} aria-label="Cerrar inspección"><X size={18}/></button><Eyebrow icon={Activity}>NODE INSPECTION / LIVE</Eyebrow><h2 id="inspection-title">{selectedNode}</h2><div className="node-status"><span className="live-dot"/> ONLINE <span>HEALTHY</span></div><div className="inspection-grid">{Object.entries(nodeData[selectedNode] ?? nodeData.Server).map(([label, value]) => <div key={label}><span>{label.toUpperCase()}</span><strong>{value}</strong></div>)}</div><div className="drawer-note"><CheckCircle2 size={16}/> Sin alertas activas en este nodo</div></aside></div>}
    {activeHardware && <div className="modal-backdrop" role="presentation" onClick={() => setActiveHardware(null)}><section className={`detail-modal hardware-modal ${activeHardware.accent}`} role="dialog" aria-modal="true" aria-labelledby="hardware-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setActiveHardware(null)} aria-label="Cerrar especificaciones"><X size={18} /></button><div className="modal-icon"><activeHardware.icon size={24} /></div><span className="card-type">{activeHardware.type}</span><h2 id="hardware-title">{activeHardware.title}</h2><p className="modal-lead">{activeHardware.detail}. Especificaciones verificadas para la arquitectura Nexus.</p><div className="hardware-specs">{activeHardware.specs.map((spec, index) => <div key={spec}><span>{index === 0 ? <Cpu size={15} /> : index === 1 ? <MemoryStick size={15} /> : index === 2 ? <Globe size={15} /> : <HardDrive size={15} />}</span>{spec}</div>)}</div></section></div>}
  </main>
}
