"use client"

import { useState } from "react"
import { ArrowRight, Cable, CheckCircle2, ChevronDown, CircleDot, Cloud, Eye, Laptop, MapPin, Menu, Network, Printer, Router, Server, ShieldCheck, Signal, SlidersHorizontal, Smartphone, Sparkles, Wifi, X, Cpu, HardDrive, MemoryStick, Globe, DollarSign } from "lucide-react"

const infrastructure = [
  { icon: Server, type: "SERVIDORES Y CONECTIVIDAD", title: "Enterprise Rack Server", detail: "Servidor central · Dilan", accent: "cyan", specs: ["Intel Xeon Silver 4310 · 12 cores", "64 GB ECC DDR4 RAM", "IP: 192.168.10.10 · 1 Gbps", "Rack 42U · UTP Cat 6"] },
  { icon: Signal, type: "SERVIDORES Y CONECTIVIDAD", title: "Módem ADSL Alta Velocidad", detail: "Backbone de acceso", accent: "cyan", specs: ["ADSL2+ · 100 Mbps downlink", "IP WAN dinámica · NAT firewall", "IP LAN: 192.168.10.1", "Uplink Cat 6 blindado"] },
  { icon: Router, type: "DISPOSITIVOS INTERMEDIOS", title: "Cisco Switching Core", detail: "Router principal · Kevin", accent: "violet", specs: ["Cisco Catalyst 9300 · 48 puertos", "StackWise · switching 1 Gbps", "IP gestión: 192.168.10.2", "VLAN 10/20/30 · PoE+"] },
  { icon: Wifi, type: "DISPOSITIVOS INTERMEDIOS", title: "Access Points Wi-Fi 6", detail: "Cobertura empresarial", accent: "violet", specs: ["802.11ax · 4x4 MU-MIMO", "2.4/5 GHz · 1.2 Gbps", "IP: 192.168.20.10–12", "Backhaul PoE+ · Cat 6 UTP"] },
  { icon: Laptop, type: "DISPOSITIVOS FINALES", title: "Workstations & PCs", detail: "2 alto rendimiento · 4 oficina", accent: "blue", specs: ["Intel Core i7 · 16 GB RAM", "SSD NVMe 512 GB", "IP: 192.168.30.20–25", "NIC 1 Gbps · Cat 6 UTP"] },
  { icon: Smartphone, type: "DISPOSITIVOS FINALES", title: "Laptops Ejecutivas", detail: "2 unidades · Emmanuel", accent: "blue", specs: ["Intel Core i5 · 16 GB RAM", "Wi-Fi 6 · WPA3 Enterprise", "DHCP: 192.168.20.50–51", "Roaming empresarial seguro"] },
  { icon: Printer, type: "PERIFÉRICOS & IOT", title: "Impresión y Vigilancia IP", detail: "Red de periféricos segura", accent: "purple", specs: ["Impresora láser de red", "Cámaras IP 1080p PoE", "VLAN IoT: 192.168.40.0/24", "Cableado Cat 6 certificado"] },
  { icon: Cloud, type: "PERIFÉRICOS & IOT", title: "Conexiones Móviles", detail: "Acceso remoto controlado", accent: "purple", specs: ["VPN SSL · AES-256", "Autenticación MFA", "Pool remoto: 10.10.10.0/24", "Firewall con inspección DPI"] },
]
const budget = [["Cables UTP Cat 6", "305 m · certificación TIA/EIA", "$8,950 MXN"], ["Cisco Switch Catalyst", "48 puertos PoE+ · C9300", "$42,500 MXN"], ["Servidor Enterprise", "Xeon · 64 GB ECC · Rack 2U", "$68,900 MXN"], ["Racks y organización", "Rack 42U · patch panels · UPS", "$24,750 MXN"], ["Mobiliario ergonómico", "6 estaciones · sillas ejecutivas", "$31,200 MXN"]]

const team = [["LL", "Luis Lopez Alcudia", "Lead Network Architect", "Topology Design", "cyan"], ["K", "Kevin", "Infrastructure Specialist", "Hardware & Switching", "violet"], ["D", "Dilan", "Server Administrator", "Security & Systems", "blue"], ["E", "Emmanuel", "Deployment Lead", "End-Devices & Systems", "purple"]]
function Eyebrow({ icon: Icon, children }: { icon: typeof Network; children: React.ReactNode }) { return <div className="eyebrow"><Icon size={14} /><span>{children}</span></div> }

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [status, setStatus] = useState(false)
  const [activeHardware, setActiveHardware] = useState<(typeof infrastructure)[number] | null>(null)
  const [budgetOpen, setBudgetOpen] = useState(false)
  return <main>
    <header className="site-header"><a href="#inicio" className="brand"><span className="brand-mark"><Network size={19} /></span><span>NEXUS <b>LAN</b><small>SOLUTIONS</small></span></a><nav className={mobileOpen ? "nav-links open" : "nav-links"} aria-label="Navegación principal"><a href="#infraestructura" onClick={() => setMobileOpen(false)}>Infraestructura</a><a href="#topologia" onClick={() => setMobileOpen(false)}>Topología LAN</a><a href="#ubicacion" onClick={() => setMobileOpen(false)}>Ubicación</a><a href="#equipo" onClick={() => setMobileOpen(false)}>Equipo</a><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú"><X size={20} /></button></nav><button className="status-button" onClick={() => setStatus(!status)}><span className="live-dot" />{status ? "Red operativa" : "Ver estado de red"}<ArrowRight size={15} /></button><button className="menu-button" onClick={() => setMobileOpen(true)} aria-label="Abrir menú"><Menu size={22} /></button></header>
    <section id="inicio" className="hero shell"><div className="hero-copy"><Eyebrow icon={Sparkles}>INFRAESTRUCTURA DE NUEVA GENERACIÓN</Eyebrow><h1>Redes que <em>conectan</em><br />el futuro.</h1><p>Diseñamos y desplegamos infraestructura LAN de nivel empresarial: alto rendimiento, topologías inteligentes y seguridad sin compromisos.</p><div className="hero-actions"><a className="button-primary" href="#topologia">Explorar topología <ArrowRight size={16} /></a><a className="button-ghost" href="#infraestructura">Especificaciones técnicas <ChevronDown size={16} /></a></div><div className="hero-trust"><CheckCircle2 size={15} /><span>Arquitectura diseñada para continuidad</span><i /><span>Villahermosa, MX</span></div></div><div className="network-dashboard"><div className="dashboard-top"><span><span className="live-dot" /> LIVE / NETWORK MONITOR</span><span>NX-01 <CircleDot size={13} /></span></div><div className="dashboard-map"><div className="map-grid" /><span className="node n1" /><span className="node n2" /><span className="node n3" /><span className="node n4" /><div className="line l1" /><div className="line l2" /><div className="line l3" /><div className="line l4" /><div className="core-node"><Network size={24} /><b>CORE</b></div><div className="map-label ml1">SERVER RACK / 01</div><div className="map-label ml2">CISCO CORE / 02</div><span className="ping-ring" /></div><div className="metrics"><div><span>LATENCIA</span><strong>1<small>ms</small></strong><i className="metric-line cyan-line" /></div><div><span>UPTIME</span><strong>99.99<small>%</small></strong><i className="metric-line violet-line" /></div><div><span>ANCHO DE BANDA</span><strong>1<small>Gbps</small></strong><i className="metric-line blue-line" /></div></div></div></section>
    <section id="infraestructura" className="section shell"><div className="section-heading"><div><Eyebrow icon={SlidersHorizontal}>SISTEMA COMPLETO</Eyebrow><h2>Infraestructura <span>sin límites.</span></h2></div><p>Un ecosistema conectado, diseñado para escalar. Cada componente cumple un rol preciso dentro de nuestra arquitectura de red.</p></div><div className="infra-grid">{infrastructure.map(({ icon: Icon, type, title, detail, accent, specs }) => <article className={`infra-card ${accent}`} key={title} role="button" tabIndex={0} onClick={() => setActiveHardware({ icon: Icon, type, title, detail, accent, specs })} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setActiveHardware({ icon: Icon, type, title, detail, accent, specs }) } }}><div className="card-icon"><Icon size={21} /></div><span className="card-type">{type}</span><h3>{title}</h3><p>{detail}</p><span className="card-hint">VER ESPECIFICACIONES</span><ArrowRight className="card-arrow" size={17} /></article>)}</div></section>
    <section id="topologia" className="section shell topology-section"><div className="section-heading"><div><Eyebrow icon={Cable}>INGENIERÍA DE RED</Eyebrow><h2>La precisión está<br /><span>en los detalles.</span></h2></div><a href="#equipo" className="text-link">Conoce al equipo <ArrowRight size={15} /></a></div><div className="topology-layout"><div className="topology-visual"><div className="topology-header"><span>LAN TOPOLOGY / DIAGRAM</span><span className="pill">ONLINE</span></div><div className="topology-canvas"><div className="rack rack-server"><Server size={19} /><span>SERVER</span></div><div className="rack rack-switch"><Router size={19} /><span>CORE SWITCH</span></div><div className="topo-lines"><i /><i /><i /><i /><i /></div><div className="endpoints"><span><Laptop size={16} /></span><span><Printer size={16} /></span><span><Wifi size={16} /></span><span><Eye size={16} /></span></div><div className="topology-caption"><span>CAT 6 / UTP</span><span>FULL DUPLEX</span><span>1 Gbps</span></div></div></div><div className="spec-panel"><div className="spec-header"><Cable size={20} /><div><span>ESTÁNDAR DE CABLEADO</span><strong>UTP CAT 6</strong></div></div><p>Canalización estructurada para máximo rendimiento y mínima interferencia electromagnética.</p><ul><li><CheckCircle2 size={16} />Rack ergonómicamente organizado</li><li><CheckCircle2 size={16} />Rutas de cableado identificadas</li><li><CheckCircle2 size={16} />Cumplimiento de seguridad física</li><li><CheckCircle2 size={16} />Mantenimiento y escalabilidad</li></ul><div className="spec-footer"><span>PROTOCOL <b>TCP/IP</b></span><span>TOPOLOGY <b>STAR</b></span></div><button className="budget-button" onClick={() => setBudgetOpen(true)}><DollarSign size={15} /> Ver presupuesto de implementación <ArrowRight size={15} /></button></div></div></section>
    <section id="ubicacion" className="location-section"><div className="shell location-layout"><div><Eyebrow icon={MapPin}>NUESTRA UBICACIÓN</Eyebrow><h2>En el centro de<br /><span>todo lo que importa.</span></h2><p>Operamos desde Villahermosa, Tabasco, conectando empresas con la infraestructura que necesitan para ir más lejos.</p><div className="address"><MapPin size={17} /><div><b>Oficinas Centrales & Datacenter</b><span>Villahermosa, Tabasco · México</span></div></div><a className="button-ghost" href="#equipo">Conocer más <ArrowRight size={15} /></a></div><div className="location-map"><div className="map-contours" /><div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" /><div className="map-pin"><MapPin size={24} /></div><span className="map-city">VILLAHERMOSA</span><span className="map-state">TABASCO, MX</span><div className="map-coords">17°59′N · 92°56′W</div></div></div></section>
    <section id="equipo" className="section shell team-section"><div className="section-heading"><div><Eyebrow icon={ShieldCheck}>EQUIPO 11 / NEXUS</Eyebrow><h2>Las personas detrás<br /><span>de la conexión.</span></h2></div><p>Especialistas que convierten la complejidad técnica en infraestructura confiable, segura y lista para el futuro.</p></div><div className="team-grid">{team.map(([initials, name, role, specialty, accent]) => <article className={`team-card ${accent}`} key={name}><div className="avatar">{initials}</div><div><h3>{name}</h3><p>{role}</p><span>{specialty}</span></div><ArrowRight size={16} /></article>)}</div></section>
    <footer className="footer"><div className="shell footer-top"><a href="#inicio" className="brand"><span className="brand-mark"><Network size={19} /></span><span>NEXUS <b>LAN</b><small>SOLUTIONS</small></span></a><p>Infraestructura que mueve<br />el mundo.</p><div className="footer-meta"><span>CBTis 163</span><span>Clasifica y Diseña la Red LAN</span><span>Prof. Franklin Quevedo · Grupo 5º B</span></div></div><div className="shell footer-bottom"><span>© 2024 Nexus LAN Solutions. All rights reserved.</span><span>NETWORK STATUS <i className="live-dot" /> OPERATIONAL</span></div></footer>
    {budgetOpen && <div className="modal-backdrop" role="presentation" onClick={() => setBudgetOpen(false)}><section className="detail-modal budget-modal" role="dialog" aria-modal="true" aria-labelledby="budget-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setBudgetOpen(false)} aria-label="Cerrar presupuesto"><X size={18} /></button><Eyebrow icon={DollarSign}>INVERSIÓN DE INFRAESTRUCTURA</Eyebrow><h2 id="budget-title">Presupuesto <span>LAN completo.</span></h2><p className="modal-lead">Desglose estimado para el despliegue empresarial en Villahermosa.</p><div className="budget-table">{budget.map(([item, description, cost]) => <div className="budget-row" key={item}><div><strong>{item}</strong><span>{description}</span></div><b>{cost}</b></div>)}</div><div className="budget-total"><span>INVERSIÓN TOTAL ESTIMADA</span><strong>$176,300 <small>MXN</small></strong></div></section></div>}
    {activeHardware && <div className="modal-backdrop" role="presentation" onClick={() => setActiveHardware(null)}><section className={`detail-modal hardware-modal ${activeHardware.accent}`} role="dialog" aria-modal="true" aria-labelledby="hardware-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setActiveHardware(null)} aria-label="Cerrar especificaciones"><X size={18} /></button><div className="modal-icon"><activeHardware.icon size={24} /></div><span className="card-type">{activeHardware.type}</span><h2 id="hardware-title">{activeHardware.title}</h2><p className="modal-lead">{activeHardware.detail}. Especificaciones verificadas para la arquitectura Nexus.</p><div className="hardware-specs">{activeHardware.specs.map((spec, index) => <div key={spec}><span>{index === 0 ? <Cpu size={15} /> : index === 1 ? <MemoryStick size={15} /> : index === 2 ? <Globe size={15} /> : <HardDrive size={15} />}</span>{spec}</div>)}</div></section></div>}
  </main>
}
